/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicVB5WWszWjdXVlRRdVJKKzVlL1pRTGFlMUhiTFBlaVZhSWZPQzBIOUQzaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaFJWYWRZY1ByWEIxTDZ6VHZHVVVIOWJGQnl3RFlJVHhSOXlkK0s5UG9RQT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpSER0WmpURWdMekYySUtUOTIzQ2lPa3ZsV28xNWVBSEFxdTdGQXJXQ1ZrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJKeWFjc3RNTGhBZjhkMnRsNXpOUmY1NlU3VnVKTmZmcTFaWXpNb09jNTJVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlORzNzQ1BuQXNMUFBiNlVuOUdzaDNqaEt5SUZIRWlwL0QrTWhTdE1NRTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlBpTWkxbkRLME9OQlZEVGhHSHEyUEV5L01SMGJReUY3V2w5L1NPclJueEE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieU1HeVVlNzA0djlaVXR0SDBDaU9ZV1E2dGMvdjBaK2RIa2hLNzJXZ2dXMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMjNVZzNYcGF6VExvVys3T1Y0NUlHWDdqbkU4SGp3ZVR0SFVxelhmQkNTcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ijl6YWxRUDJJN0V3SUp3NlhEUXYzV3NqbTZKN3BjV21LdFJaSlFBcFVPNW1WeFRtU2lkaEcxZ0xHOXJuRURNQm5VN2VHejBtek0yQmRsTlNVcXZQZGpnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTk3LCJhZHZTZWNyZXRLZXkiOiJ6L0pzK3gvTlV6Y0FHY2FkZ05OR3FBMFdKejdZWW5ydzZHb296a0R2a1JzPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcxMDY2NTExNkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJGN0E2MjIzMTAzMkY3MDg5MkI5NDBERjY4RDVCNzE2QyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMxNDM0ODgzfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3MTA2NjUxMTZAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNUE2RTY2QzY1QkU0RjUxMTkxOTQ5NTJBNzZEMkJCNUYifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczMTQzNDg4M31dLCJuZXh0UHJlS2V5SWQiOjMyLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzIsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiZDFvSHBkd2FTd3FkWl9GNG5qdzdUUSIsInBob25lSWQiOiJlZTZmMzhiYy03NTVlLTQ3ODAtODM4Yy02MWZiMGUyMTdjODQiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZFByc2plUmY3MGRmUmlJNXpaNUprNDA1c0xjPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ii9ZOW1EVzdyMjYzcDMxcHMwMnk1TnRkVVRORT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJGWlM3TkZFQSIsIm1lIjp7ImlkIjoiMjU0NzEwNjY1MTE2OjcyQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkxvcmVlIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNQcWF0R3NRNkxMT3VRWVlDaUFBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiIxOWZjL0xITWNSL2p6Qk55a1I1NzNPNm82NnFhbzA4NXRmNzZGampiRmlrPSIsImFjY291bnRTaWduYXR1cmUiOiIvM1M3cWhWdVdpRWpCdnYzVE0xTXBvdFVnN3NibzJzaVgvbVhQYk5YTndGaXZFT0R1WTU3MUNyelQzWS9qR0ZzRDRxNXF2STJGcmxDWTFKV0ZXMHpEQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiYTFIZU5tak9nU0VpM2FQZGIzN0lyVHVMTFBRbm91SDZLTXo2N0VWVnRtdHNUWTRyeXdieHM2ZjRhVkwrQS9XRm03dE9rMkpKRzhrUW55RTNoM1ZTaEE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3MTA2NjUxMTY6NzJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZGZYM1B5eHpIRWY0OHdUY3BFZWU5enVxT3VxbXFOUE9iWCsraFk0MnhZcCJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMTQzNDg3MCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFFMUsifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254710665116';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'private';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'false';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'false';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
autolike,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
